name: edochub_b2b
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^8.0.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  flutter_staggered_animations: ^1.1.1
  http: ^1.2.1
  file_picker: ^10.3.8
  get: ^4.6.6
  flutter_animate: ^4.5.0
  animations: ^2.0.11
  dio: ^5.5.0+1
  intl: ^0.20.2
  permission_handler: ^12.0.1
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#4C6A4E"
